# release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Major Changes
      labels:
        - Semver-Major
        - major-change
    - title: New Features & Enhancements
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
